name: Builds

on:
  pull_request:
    branches:
      - master

jobs:
  lint-repo:
    name: Lint & format code
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: go fmt
        run: if [ "$(make fmt_list | wc -l)" -gt 1 ]; then exit 1; fi
  test-repo:
    name: Run `go test`
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: make test
  build-image:
    name: Run `go build`
    runs-on: self-hosted